### ISSUE TITLE
Feature Request: Support word count like Microsoft Word

### ISSUE THREAD

**Issue by Vxider** [holmescn/vscode-wordcount-cjk#2]
Hope I can set the status bar to count word like Microsoft Word(non-ascii + en-words), or if I can edit the `statusBarTextTemplate` like
```
    "wordcount_cjk.statusBarTextTemplate": "共 $((${non-ascii} + ${en-words})) 字"
```

**Comment by holmesconan** [comment]
Sorry for the late response.
First, you could do that, except you format string maybe error, which should be "共 ${non-ascii} - ${en-words} 字 ".
Second, since my extension do not support configuration hot reload, you need to restart the vscode after specify the format string.

Thank you for your issue.

**Comment by Vxider** [comment]
Thanks for your help.
I have set my format string to :
<img width="734" alt="2018-01-23 10 54 42" src="https://user-images.githubusercontent.com/6134315/35255803-dbd6815c-002b-11e8-998b-d00c4b903d18.png">
and restart vscode, then my status bar was like this:
<img width="140" alt="2018-01-23 10 54 49" src="https://user-images.githubusercontent.com/6134315/35255823-f1357b52-002b-11e8-9a1c-3e9db8d6f2ba.png">
I hope it can be automatically added, in this example ,it should be `共9116字`

**Comment by holmesconan** [comment]
if I understand what you want is: calculate in format text?

**Comment by Vxider** [comment]
Yes

**Comment by holmesconan** [comment]
@Vxider OK, I will try to implement that.

**Comment by Vxider** [comment]
Thanks

**Comment by holmesconan** [comment]
@Vxider A new version is released. Try it!

**Comment by Vxider** [comment]
Thanks
