### ISSUE TITLE
[Feature request] support for Rmarkdown files

### ISSUE THREAD

**Issue by psychelzh** [holmescn/vscode-wordcount-cjk#3]
`Markdown` is extended by `pandoc` and `RStudio`'s `Rmarkdown`, whose extension is `.Rmd`. I wonder how these files can count words automatically.

**Comment by holmesconan** [comment]
@psychelzh Sorry for the late response. The newest version could be activated by `.editorconfig` file if it exists in the project folder. You can try it.

**Comment by holmesconan** [comment]
@psychelzh A new version 1.2.0 is released. Now you have two methods to activate this extension for any kinds of file:

1. Use `Word Count Activate` and `Word Count Deactivate` commands
2. Use `wordcount_cjk.activateLanguages` configuration.

Have Fun!

**Comment by psychelzh** [comment]
@holmescn Thanks very much. It is of huge improvement now!
